test EvecCache for one-band system
Needed to switch from linxal OpenBLAS default to netlib to get build working.
Got linking error:
    lapack-0.11.4/src/c.rs:3783: undefined reference to `LAPACKE_zheev'